<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260305123515 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE facture_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(180) NOT NULL, quantite INT NOT NULL, prix_unitaire INT NOT NULL, total INT NOT NULL, type VARCHAR(30) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facture_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5C453347F2DEE08 ON facture_ligne (facture_id)');
        $this->addSql('CREATE TABLE paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant INT NOT NULL, mode VARCHAR(20) NOT NULL, paye_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facture_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E7F2DEE08 ON paiement (facture_id)');
        $this->addSql('ALTER TABLE facture_ligne ADD CONSTRAINT FK_C5C453347F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E7F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cim10_code ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE cim10_code ADD modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE examen_demande ADD prix_unitaire NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE examen_demande ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE examen_demande ADD modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE facture_ligne DROP CONSTRAINT FK_C5C453347F2DEE08');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E7F2DEE08');
        $this->addSql('DROP TABLE facture_ligne');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('ALTER TABLE cim10_code DROP created_at');
        $this->addSql('ALTER TABLE cim10_code DROP modified_at');
        $this->addSql('ALTER TABLE examen_demande DROP prix_unitaire');
        $this->addSql('ALTER TABLE examen_demande DROP created_at');
        $this->addSql('ALTER TABLE examen_demande DROP modified_at');
    }
}
