<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260305142740 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bon_examen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_demande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) NOT NULL, token VARCHAR(64) NOT NULL, note TEXT DEFAULT NULL, consultation_id INT DEFAULT NULL, patient_id INT NOT NULL, medecin_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4530F7D65F37A13B ON bon_examen (token)');
        $this->addSql('CREATE INDEX IDX_4530F7D662FF6CDF ON bon_examen (consultation_id)');
        $this->addSql('CREATE INDEX IDX_4530F7D66B899279 ON bon_examen (patient_id)');
        $this->addSql('CREATE INDEX IDX_4530F7D64F31A84 ON bon_examen (medecin_id)');
        $this->addSql('CREATE TABLE bon_examen_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, urgence BOOLEAN DEFAULT NULL, note TEXT DEFAULT NULL, resultat_valeur VARCHAR(255) DEFAULT NULL, unite VARCHAR(50) DEFAULT NULL, valeurs_normales VARCHAR(255) DEFAULT NULL, resultat_texte TEXT DEFAULT NULL, resultat_saisi_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, piece_jointe_path VARCHAR(255) DEFAULT NULL, prix_unitaire NUMERIC(10, 2) DEFAULT NULL, bon_id INT NOT NULL, resultat_saisi_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65C1F3EAAD65737C ON bon_examen_ligne (bon_id)');
        $this->addSql('CREATE INDEX IDX_65C1F3EA7FF20340 ON bon_examen_ligne (resultat_saisi_par_id)');
        $this->addSql('ALTER TABLE bon_examen ADD CONSTRAINT FK_4530F7D662FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen ADD CONSTRAINT FK_4530F7D66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen ADD CONSTRAINT FK_4530F7D64F31A84 FOREIGN KEY (medecin_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen_ligne ADD CONSTRAINT FK_65C1F3EAAD65737C FOREIGN KEY (bon_id) REFERENCES bon_examen (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen_ligne ADD CONSTRAINT FK_65C1F3EA7FF20340 FOREIGN KEY (resultat_saisi_par_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bon_examen DROP CONSTRAINT FK_4530F7D662FF6CDF');
        $this->addSql('ALTER TABLE bon_examen DROP CONSTRAINT FK_4530F7D66B899279');
        $this->addSql('ALTER TABLE bon_examen DROP CONSTRAINT FK_4530F7D64F31A84');
        $this->addSql('ALTER TABLE bon_examen_ligne DROP CONSTRAINT FK_65C1F3EAAD65737C');
        $this->addSql('ALTER TABLE bon_examen_ligne DROP CONSTRAINT FK_65C1F3EA7FF20340');
        $this->addSql('DROP TABLE bon_examen');
        $this->addSql('DROP TABLE bon_examen_ligne');
    }
}
